version: 0.2
env:
  variables:
    PACKAGE: "github.com/arthurflame/Tasks"
    APP_NAME: "Tasks"
phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
  pre_build:
    commands:
#      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get update && apt-get -y install sqlite3
      - cd "/go/src/${PACKAGE}"
#      - go mod init $APP_NAME
#      - go mod tidy
#      - go install
#      - go get -d -u ./...
      - go get -t ./...
      - cat schema.sql | sqlite3 tasks.db
  build:
    commands:
      - go build -o application
      - echo $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
  post_build:
    commands:
      - zip ./${APP_NAME}.zip -r * .[^.]*


artifacts:
  files:
    - '${APP_NAME}.zip'
